version: "3.3"
services:
  elasticsearch:
    build:
      context: ./elasticsearch
    container_name: elasticsearch    
    image: elasticsearch-backend
    ports:
      - '9200:9200'
      - '9300:9300'

  flask-python:
    build:
      context: ./python
    container_name: python-flask
    image: python-flask
    ports:
      - '80:3001'
    depends_on:
      - elasticsearch